name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Set up Python 3.8.18
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.18'
    - name: Check Python version
      run: python --version


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
